"""
Mock responses for AI assistants for testing purposes.
"""

def get_mock_response() -> str:
    """
    Get a mock response for testing purposes.

    Returns:
        A string with a mock response
    """
    return (
        "I'll help you create a page for your dog Athena! I'll use the O1 reasoning engine to plan and create the necessary files.\n\n"
        "First, let me check if there are any existing files in your vibe directory:\n\n"
        "```tool\n"
        "list_files\n"
        "```\n\n"
        "Let me check if there are any existing images we can use:\n\n"
        "```tool\n"
        "list_images\n"
        "```\n\n"
        "Let me generate a new image of a cute dog for Athena's page:\n\n"
        "```tool\n"
        "generate_image\n"
        "prompt: A cute golden retriever dog named Athena, photorealistic\n"
        "size: 1024x1024\n"
        "filename: athena_dog.png\n"
        "```\n\n"
        "Now I'll create an index.html file for Athena's page that includes the image:\n\n"
        "```tool\n"
        "write_file\n"
        "filename: index.html\n"
        "content:\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Athena - The Amazing Dog</title>\n"
        "    <link rel=\"stylesheet\" href=\"style.css\">\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <header>\n"
        "            <h1>Athena</h1>\n"
        "            <p class=\"subtitle\">The Most Wonderful Dog</p>\n"
        "        </header>\n"
        "        \n"
        "        <div class=\"dog-profile\">\n"
        "            <div class=\"dog-image\">\n"
        "                <!-- Image wrapped in a link to an external website, using IPFS URL as primary source -->\n"
        "                <a href=\"https://en.wikipedia.org/wiki/Golden_Retriever\" target=\"_blank\">\n"
        "                    <img src=\"https://ipfs.io/ipfs/example-hash\" alt=\"A cute golden retriever dog named Athena\" class=\"dog-photo\" data-local-path=\"/static/vibes/vibe-slug/athena_dog.png\">\n"
        "                </a>\n"
        "            </div>\n"
        "            \n"
        "            <div class=\"dog-info\">\n"
        "                <h2>About Athena</h2>\n"
        "                <p>Athena is an amazing dog who brings joy and happiness to everyone around her. She's playful, loyal, and incredibly smart!</p>\n"
        "                \n"
        "                <div class=\"dog-stats\">\n"
        "                    <div class=\"stat\">\n"
        "                        <span class=\"stat-label\">Cuteness</span>\n"
        "                        <div class=\"stat-bar\">\n"
        "                            <div class=\"stat-fill\" style=\"width: 100%;\"></div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                    <div class=\"stat\">\n"
        "                        <span class=\"stat-label\">Playfulness</span>\n"
        "                        <div class=\"stat-bar\">\n"
        "                            <div class=\"stat-fill\" style=\"width: 95%;\"></div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                    <div class=\"stat\">\n"
        "                        <span class=\"stat-label\">Loyalty</span>\n"
        "                        <div class=\"stat-bar\">\n"
        "                            <div class=\"stat-fill\" style=\"width: 100%;\"></div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                    <div class=\"stat\">\n"
        "                        <span class=\"stat-label\">Intelligence</span>\n"
        "                        <div class=\"stat-bar\">\n"
        "                            <div class=\"stat-fill\" style=\"width: 90%;\"></div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"dog-gallery\">\n"
        "            <h2>Athena's Favorite Activities</h2>\n"
        "            <div class=\"activities\">\n"
        "                <div class=\"activity\">\n"
        "                    <!-- Image link to another page in the vibe -->\n"
        "                    <a href=\"activities.html\">\n"
        "                        <div class=\"activity-icon\">🦴</div>\n"
        "                        <p>Chewing Bones</p>\n"
        "                    </a>\n"
        "                </div>\n"
        "                <div class=\"activity\">\n"
        "                    <div class=\"activity-icon\">🏃‍♀️</div>\n"
        "                    <p>Running</p>\n"
        "                </div>\n"
        "                <div class=\"activity\">\n"
        "                    <div class=\"activity-icon\">🎾</div>\n"
        "                    <p>Fetching Balls</p>\n"
        "                </div>\n"
        "                <div class=\"activity\">\n"
        "                    <div class=\"activity-icon\">😴</div>\n"
        "                    <p>Napping</p>\n"
        "                </div>\n"
        "            </div>\n"
        "        </div>\n"
        "        \n"
        "        <footer>\n"
        "            <p>Made with ❤️ for Athena</p>\n"
        "            <button id=\"treat-button\">Give Athena a Treat!</button>\n"
        "        </footer>\n"
        "    </div>\n"
        "    <script src=\"script.js\"></script>\n"
        "</body>\n"
        "</html>\n"
        "```\n\n"
        "Now I'll create a style.css file to make Athena's page look beautiful:\n\n"
        "```tool\n"
        "write_file\n"
        "filename: style.css\n"
        "content:\n"
        "* {\n"
        "    box-sizing: border-box;\n"
        "    margin: 0;\n"
        "    padding: 0;\n"
        "}\n"
        "\n"
        "body {\n"
        "    font-family: 'Arial', sans-serif;\n"
        "    background-color: #f8f9fa;\n"
        "    color: #333;\n"
        "    line-height: 1.6;\n"
        "}\n"
        "\n"
        "/* More CSS content would go here */\n"
        "```\n\n"
        "I've created the main files for Athena's page!"
    )
